version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.01
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version -f "{{ .Server.Experimental }}"
      - run: sudo systemctl restart docker --experimental
      - run: docker version -f "{{ .Server.Experimental }}"
